[build.environment]
  # Secrets scanning configuration to ignore Firebase API keys
  SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "AIza,firebase,googleapis"
SECRETS_SCAN_SMART_DETECTION_ENABLED = "true"